import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import { AppProviders } from './providers';
import ClientLayout from "@/layout/ClientLayout";


export const outfit = localFont({
  src: [
    { path: '../fonts/outfit/Outfit-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/outfit/Outfit-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../fonts/outfit/Outfit-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../fonts/outfit/Outfit-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-outfit',
  display: 'swap',
});

export const inter = localFont({
  src: [
    { path: '../fonts/inter/Inter-Light.woff2', weight: '300', style: 'normal' },
    { path: '../fonts/inter/Inter-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/inter/Inter-Medium.woff2', weight: '500', style: 'normal' },
  ],
  variable: '--font-inter',
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${outfit.variable} ${inter.variable}`} suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#3e3e42" />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/icon-192.png" />
        <link rel="apple-touch-icon" href="/icons/icon-192.png" />

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>

      <body>
        <AppProviders>
          <ClientLayout>
            {children}
          </ClientLayout>
        </AppProviders>
      </body>
    </html>
  );
}
